# Generated by Django 3.2 on 2021-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bookdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='user',
            field=models.EmailField(max_length=100),
        ),
    ]
